from pathlib import Path
import re

path = Path('/home/ubuntu/hael-studio/client/src/pages/Home.tsx')
text = path.read_text()
start = text.index('            {mode === "preview" && <div className="preview-runtime">')
end = text.index('            {mode === "simulate" &&', start)
block = '''            {mode === "preview" && <div className="preview-runtime">
              <div className="runtime-toolbar"><div className="runtime-route"><span className="runtime-traffic"><i /><i /><i /></span><span>lineage.gqobonco.studio</span><StatusPill tone="green"><span className="pulse-dot" /> runtime ready</StatusPill></div><div className="runtime-toolbar-actions"><button onClick={replayScenario}><RotateCcw size={13} /> Replay</button><button onClick={() => setMode("simulate")}><Play size={13} /> Simulate</button></div></div>
              <div className="runtime-controls"><label>Device<select value={device} onChange={(event) => setDevice(event.target.value)}><option>Desktop</option><option>Tablet</option><option>Mobile</option></select></label><label>Language<select value={language} onChange={(event) => setLanguage(event.target.value)}><option>isiXhosa</option><option>English</option><option>Orren</option></select></label><label>Persona<select value={persona} onChange={(event) => setPersona(event.target.value)}><option>Researcher</option><option>First-time visitor</option><option>Reviewer</option></select></label></div>
              <div className="preview-runtime-body">
                <div className="preview-stage-strip"><div className="preview-stages">{(["icon", "entry", "running", "media", "exit"] as const).map((stage) => <button key={stage} onClick={() => setPreviewStage(stage)} className={cn(previewStage === stage && "active")}><span>{stage === "icon" ? "◇" : stage === "entry" ? "↗" : stage === "running" ? "●" : stage === "media" ? "◒" : "×"}</span>{stage}</button>)}</div><div className="artifact-switcher"><button className={artifactType === "application" ? "active" : ""} onClick={() => setArtifactType("application")}><Boxes size={12} /> App</button><button className={artifactType === "video" ? "active" : ""} onClick={() => setArtifactType("video")}><Play size={12} /> Video</button><button className={artifactType === "music" ? "active" : ""} onClick={() => setArtifactType("music")}><Radio size={12} /> Music</button></div></div>
                <div className="preview-identity"><span className="eyebrow">A living research archive</span><span className="preview-runtime-state"><span className="pulse-dot" /> {activeEvent ? activeEvent.label : "Awaiting first signal"}</span></div>
                <h3>{artifactType === "application" ? <>Knowledge does not disappear.<br /><em>It changes hands.</em></> : artifactType === "video" ? <>A moving image<br /><em>can remember a place.</em></> : <>Let the signal<br /><em>find its rhythm.</em></>}</h3>
                <p>{previewStage === "icon" ? "Checking the identity mark before entry." : previewStage === "entry" ? `Welcome, ${persona.toLowerCase()}. This threshold is speaking in ${language}.` : previewStage === "running" ? "The application is moving through its live state." : previewStage === "media" ? "Media playback is isolated from the application runtime." : "The experience has exited cleanly and left its trace."}</p>
                <div className="preview-runtime-card"><div className="preview-orbit"><span /><span /><span /></div><div><span className="eyebrow">Current runtime state</span><strong>{activeEvent ? activeEvent.detail : "The experience is ready to receive a visitor."}</strong><small>{device} · {language} · {persona}</small></div></div>
                {artifactType === "video" && <div className="video-runtime"><video ref={videoRef} src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" poster={canvasArt} onTimeUpdate={(event) => { const video = event.currentTarget; setMediaTime(Math.round((video.currentTime / Math.max(1, video.duration)) * 100)); }} onEnded={() => { setMediaPlaying(false); setMediaEventLog((current) => ["video.ended", ...current].slice(0, 5)); }} /><div className="video-overlay"><button onClick={toggleVideoPlayback}>{mediaPlaying ? <Pause size={14} /> : <Play size={14} />}</button><span>{mediaPlaying ? "Playing video sandbox" : "Video ready"}</span><StatusPill tone="green">isolated</StatusPill></div></div>}
                {artifactType === "music" && <div className="audio-runtime"><div className="audio-wave"><span /><span /><span /><span /><span /><span /><span /><span /><span /><span /></div><div className="audio-runtime-meta"><div><span className="eyebrow">Sound sandbox</span><strong>{audioPlaying ? "Startup tone is sounding" : "Sound ready to preview"}</strong><small>Web Audio · isolated from app runtime</small></div><StatusPill tone={audioPlaying ? "green" : "gold"}>{audioPlaying ? "Playing" : "Stopped"}</StatusPill></div><button className="audio-primary" onClick={toggleSound}>{audioPlaying ? <Pause size={14} /> : <Play size={14} />} {audioPlaying ? "Stop sound" : "Play sound"}</button></div>}
                {artifactType !== "application" && <div className="media-control"><button className="media-play" onClick={() => artifactType === "video" ? toggleVideoPlayback() : toggleSound()}>{(artifactType === "video" ? mediaPlaying : audioPlaying) ? <Pause size={14} /> : <Play size={14} />}</button><div className="media-track"><span style={{ width: `${mediaTime}%` }} /><input aria-label="Media playback position" type="range" min="0" max="100" value={mediaTime} onChange={(event) => setMediaTime(Number(event.target.value))} /></div><span className="media-time">{mediaTime}%</span><div className="volume-wrap"><button onClick={() => setMediaMuted(!mediaMuted)} aria-label="Toggle mute">{mediaMuted ? "×" : "◖"}</button><input aria-label="Media volume" type="range" min="0" max="100" value={mediaVolume} onChange={(event) => setMediaVolume(Number(event.target.value))} /></div></div>}
                <div className="effect-timeline"><div className="effect-timeline-head"><div><span className="eyebrow">Full effect timeline</span><strong>{selectedEffect.label}</strong><small>{selectedEffect.detail}</small></div><div className="effect-head-actions"><StatusPill tone={effectPlaying ? "green" : "gold"}>{effectPlaying ? "Replaying" : `Pass ${effectReplayCount + 1}`}</StatusPill><button onClick={replayEffects}><RotateCcw size={13} /> Replay</button></div></div><div className="effect-ruler"><span>00:00</span><span>00:05</span><span>00:10</span><span>00:15</span><span>00:20</span></div><div className="effect-track"><span className="effect-playhead" style={{ left: `${(effectTime / 20) * 100}%` }} /><div className="effect-lanes">{(["frame", "audio", "animation", "lifecycle", "interaction"] as EffectKind[]).map(renderEffectLane)}</div></div><div className="effect-timeline-controls"><div><button className="effect-control-primary" onClick={() => setEffectPlaying(!effectPlaying)}>{effectPlaying ? <Pause size={13} /> : <Play size={13} />} {effectPlaying ? "Pause" : "Play"}</button><button onClick={() => stepEffect(-1)}><StepBack size={13} /></button><button onClick={() => stepEffect(1)}><StepForward size={13} /></button></div><label>Playhead <input aria-label="Effect timeline playhead" type="range" min="0" max="20" value={effectTime} onChange={(event) => setEffectTime(Number(event.target.value))} /><span>00:{String(effectTime).padStart(2, "0")}</span></label><label>Speed <select value={effectSpeed} onChange={(event) => setEffectSpeed(Number(event.target.value))}><option value={0.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select></label></div><div className="effect-selected-detail"><span className={cn("effect-kind-icon", `effect-${selectedEffect.kind}`)}>{effectIcon(selectedEffect.kind)}</span><div><strong>{selectedEffect.time.toString().padStart(2, "0")}s · {selectedEffect.kind}</strong><small>trigger: {selectedEffect.trigger}</small></div><StatusPill tone="neutral">{activeEffect?.id === selectedEffect.id ? "At playhead" : "Inspectable"}</StatusPill></div><div className="effect-inspector"><div><span className="eyebrow">Motion intensity</span><small>{mediaEventLog.length ? mediaEventLog.join(" · ") : "No effects fired yet"}</small></div><input aria-label="Effect intensity" type="range" min="0" max="100" value={effectIntensity} onChange={(event) => setEffectIntensity(Number(event.target.value))} /><StatusPill tone="neutral">{effectIntensity}%</StatusPill></div></div>
                <div className="preview-progress"><span style={{ width: `${Math.max(8, (runtimeTime / activeScenario.duration) * 100)}%` }} /></div><div className="preview-runtime-footer"><small>{Math.round((runtimeTime / activeScenario.duration) * 100)}% of scenario elapsed · {previewStage} stage</small><div><button onClick={advancePreviewStage}><StepForward size={13} /> Next stage</button><button onClick={() => setMode("simulate")}><Activity size={13} /> View live events</button></div></div>
              </div>
            </div>}
'''
path.write_text(text[:start] + block + text[end:])
print('rewrote preview block')
